[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "15.5.1"
  NPM_VERSION = "7.3.0"

[context.production]
  command = "npx hugo --gc --minify && npx netlify-lambda build assets/lambda"

[context.deploy-preview]
  command = "npx hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npx hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next]
  command = "npx hugo --gc --minify && npx netlify-lambda build assets/lambda"

[context.next.environment]
  HUGO_ENV = "next"

[[headers]]
  for = "*/"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"
    Access-Control-Allow-Origin = "*"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; frame-ancestors https://jamstackthemes.dev; manifest-src 'self'; connect-src 'self'; font-src 'self; img-src 'self' data:; script-src 'self'; style-src 'self'"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin"
    Feature-Policy = "geolocation 'self'"
    X-Nf-Request-Id = "e0a5dd13-5c7a-4d54-b7d5-02a5e9f084f6"

[dev]
  framework = "#custom"
  command = "npx rimraf public resources functions && npx hugo server --bind=0.0.0.0 --disableFastRender"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false
